Repository Princeton-LSI-ResearchComputing/tracebase, pull requests merged in 2024-05, with the labels that each got.

#957 Add Iso-Autocorr DataFormat to fixtures
  DataRepo/fixtures/data_formats.yaml
Labels: component:8-loading

#913 Linked the treatment in the PeakData advanced search results
  DataRepo/templates/DataRepo/search/results/peakdata.html
Labels: component:2-templates

#948 Groundwork for loading mzXML files independent of accucor data
  DataRepo/data/tests/submission_v3/defaults.tsv
  DataRepo/data/tests/submission_v3/lcprotocols.tsv
  DataRepo/data/tests/submission_v3/sequences.tsv
  DataRepo/data/tests/submission_v3/study.xlsx
  DataRepo/data/tests/submission_v3/study_no_defs.xlsx
  DataRepo/loaders/lcprotocols_loader.py
  DataRepo/loaders/sequences_loader.py
  DataRepo/loaders/table_loader.py
  DataRepo/management/commands/load_lcprotocols.py
  DataRepo/tests/loaders/test_lcprotocols_loader.py
  DataRepo/tests/loaders/test_sequences_loader.py
  DataRepo/tests/management/test_load_lcprotocols.py
  DataRepo/tests/utils/test_exceptions.py
  DataRepo/tests/utils/test_file_utils.py
  DataRepo/utils/exceptions.py
Labels: component:8-loading

#949 MSRunSample unique constraint code version of null == null
  DataRepo/loaders/accucor_data_loader.py
  DataRepo/migrations/0037_alter_msrunsample_options_and_more.py
  DataRepo/models/__init__.py
  DataRepo/models/msrun_sample.py
  DataRepo/models/utilities.py
  DataRepo/tests/management/test_load_accucor_msruns.py
  DataRepo/tests/models/test_utilities.py
Labels: component:8-loading

#900 TracersLoader
  DataRepo/loaders/tracers_loader.py
  DataRepo/tests/loaders/test_tracers_loader.py
Labels: component:8-loading

#901 load_tracers
  DataRepo/data/tests/tracers/lysine_data_only.tsv
  DataRepo/data/tests/tracers/lysine_full.tsv
  DataRepo/data/tests/tracers/lysine_name_only.tsv
  DataRepo/data/tests/tracers/lysine_name_only.xlsx
  DataRepo/data/tests/tracers/lysine_not_fully_labeled.tsv
  DataRepo/data/tests/tracers/tracers_with_errors.tsv
  DataRepo/data/tests/tracers/two_dual_labeled_isoptopes.tsv
  DataRepo/loaders/__init__.py
  DataRepo/management/commands/load_tracers.py
  DataRepo/tests/management/test_load_tracers.py
  DataRepo/utils/exceptions.py
Labels: component:8-loading

#962 MSRunsLoader
  .jscpd.json
  DataRepo/data/tests/submission_v3/defaults.tsv
  DataRepo/formats/dataformat_group_query.py
  DataRepo/loaders/accucor_data_loader.py
  DataRepo/loaders/compounds_loader.py
  DataRepo/loaders/lcprotocols_loader.py
  DataRepo/loaders/msruns_loader.py
  DataRepo/loaders/protocols_loader.py
  DataRepo/loaders/sample_table_loader.py
  DataRepo/loaders/sequences_loader.py
  DataRepo/loaders/study_table_loader.py
  DataRepo/loaders/table_loader.py
  DataRepo/loaders/tissues_loader.py
  DataRepo/management/commands/load_msruns.py
  DataRepo/management/commands/load_table.py
  DataRepo/models/archive_file.py
  DataRepo/models/lc_method.py
  DataRepo/models/msrun_sample.py
  DataRepo/models/peak_group.py
  DataRepo/models/utilities.py
  DataRepo/tests/loaders/test_msruns_loader.py
  DataRepo/tests/loaders/test_table_loader.py
  DataRepo/tests/management/test_load_accucor_msruns.py
  DataRepo/tests/management/test_load_lcms_metadata.py
  DataRepo/tests/management/test_load_msruns.py
  DataRepo/tests/management/test_load_table.py
  DataRepo/tests/management/test_load_tissues.py
  DataRepo/tests/models/test_archive_file.py
  DataRepo/tests/models/test_msrun_sample.py
  DataRepo/tests/models/test_msrun_sequence.py
  DataRepo/tests/models/test_peak_group.py
  DataRepo/tests/models/test_utilities.py
  DataRepo/tests/utils/test_exceptions.py
  DataRepo/tests/views/upload/test_validation.py
  DataRepo/utils/__init__.py
  DataRepo/utils/exceptions.py
  DataRepo/views/upload/validation.py
Labels: component:8-loading

#965 Placeholder data migration rewrite
  DataRepo/loaders/msruns_loader.py
  DataRepo/migrations/0037_msrunsample_null_eq_null_data_migration.py
  DataRepo/migrations/0038_alter_msrunsample_unique_constraint.py
  DataRepo/templates/DataRepo/archive_file_detail.html
Labels: component:6-models

#960 Add function to detect peak annotation DataFormat
  DataRepo/loaders/accucor_data_loader.py
  DataRepo/tests/loaders/test_accucor_data_loader.py
  DataRepo/utils/exceptions.py
Labels: component:8-loading

#961 Autodetect peakannotation format
  DataRepo/loaders/accucor_data_loader.py
  DataRepo/management/commands/load_accucor_msruns.py
  DataRepo/tests/management/test_load_accucor_msruns.py
  DataRepo/tests/management/test_load_lcms_metadata.py
  DataRepo/tests/test_views.py
Labels: component:8-loading
