Repository Princeton-LSI-ResearchComputing/tracebase, pull requests merged in 2025-05, with the labels that each got.

#1521 Another single label position bug
  DataRepo/data/tests/load_study/single_tracer_label_position.xlsx
  DataRepo/management/commands/load_study.py
  DataRepo/management/commands/load_table.py
  DataRepo/tests/management/commands/test_load_study.py
  DataRepo/utils/file_utils.py
  DataRepo/views/upload/submission.py
Labels: type:bug, priority:2-high, component:loading, effort:4-under1day

#1528 Cryptic MissingSample Errors
  DataRepo/loaders/base/table_loader.py
  DataRepo/loaders/msruns_loader.py
  DataRepo/loaders/peak_annotation_files_loader.py
  DataRepo/loaders/peak_annotations_loader.py
  DataRepo/loaders/study_loader.py
  DataRepo/tests/loaders/test_msruns_loader.py
  DataRepo/tests/loaders/test_study_loader.py
  DataRepo/tests/management/commands/test_load_peak_annotation_files.py
  DataRepo/tests/management/commands/test_load_peak_annotations.py
  DataRepo/tests/utils/test_exceptions.py
  DataRepo/tests/utils/test_infusate_parser.py
  DataRepo/tests/views/upload/test_submission.py
  DataRepo/utils/exceptions.py
  DataRepo/utils/infusate_name_parser.py
Labels: type:bug, priority:2-high, component:loading, effort:3-under1wk

#1531 The comparison select list on the advanced search gets reset each time you search
  static/js/hierarchical_formsets.js
Labels: type:bug, priority:3-medium, component:search, effort:5-under1hr

#1536 Advanced Search Stats bug fix
  DataRepo/formats/dataformat.py
  DataRepo/models/utilities.py
  DataRepo/tests/models/test_utilities.py
  DataRepo/tests/views/search/test_download.py
Labels: type:bug, priority:2-high, component:search, effort:4-under1day

#1537 Remove the compound version numbers that ELMaven appends
  DataRepo/data/tests/data_submission/accucor3_with_elmaven_compound_numbers.xlsx
  DataRepo/loaders/peak_annotations_loader.py
  DataRepo/tests/loaders/test_peak_annotations_loader.py
  DataRepo/tests/views/upload/test_submission.py
  DataRepo/views/upload/submission.py
Labels: type:feature, priority:2-high, component:loading, component:submission, effort:4-under1day, component:tests, component:views

#1534 Parsing Isotope Error
  DataRepo/utils/infusate_name_parser.py
  DataRepo/views/upload/submission.py
Labels: type:bug, priority:3-medium, component:validation, component:submission

#1540 Only abort an `MSRunsLoader` load when the missing samples don't appear to be blanks
  DataRepo/loaders/msruns_loader.py
Labels: type:bug, priority:2-high, component:loading, status:approved, effort:4-under1day

#1557 Missing FCirc Value Warning
  DataRepo/loaders/animals_loader.py
  DataRepo/loaders/samples_loader.py
  DataRepo/tests/loaders/test_animals_loader.py
  DataRepo/tests/management/commands/test_load_animals.py
  DataRepo/tests/utils/test_exceptions.py
  DataRepo/utils/exceptions.py
Labels: type:feature, priority:3-medium, component:loading, component:validation, effort:4-under1day

#1552 Prohibit use of delimiters in `Compound` names and synonyms
  DataRepo/data/tests/compounds/compounds_with_prohibited_delimiters.tsv
  DataRepo/loaders/compounds_loader.py
  DataRepo/loaders/peak_annotations_loader.py
  DataRepo/migrations/0052_alter_compound_formula_alter_compound_name_and_more.py
  DataRepo/models/compound.py
  DataRepo/models/peak_group.py
  DataRepo/tests/loaders/test_compounds_loader.py
  DataRepo/tests/loaders/test_peak_annotations_loader.py
  DataRepo/tests/models/test_compound.py
  DataRepo/tests/utils/test_exceptions.py
  DataRepo/utils/exceptions.py
Labels: type:feature, priority:3-medium, component:loading, component:validation, effort:4-under1day
